# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-11 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20171111_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseresource',
            old_name='coures',
            new_name='course',
        ),
    ]
